package eu.janschupke.buddy.framework.config.enumeration.tags;

/**
 * Enumeration of tags for all situations in the game.
 *
 * @author jan.schupke@gmail.com
 */
public enum SituationTags {
    // Forest.
    FOREST_COIN_INVESTIGATE,
    FOREST_CARAVAN_INVESTIGATE,

    FOREST_UKKO_TALK,
    FOREST_UKKO_DISCUSS,
    FOREST_UKKO_DELIVERY_RESULT,

    // Outskirts.
    OUTSKIRTS_LUMBER_INVESTIGATE,
    OUTSKIRTS_ROAD_SIGN_INVESTIGATE,
    OUTSKIRTS_JACK_HOUSE_INVESTIGATE,
    OUTSKIRTS_VARPUNEN_INVESTIGATE,
    OUTSKIRTS_CAVE_INVESTIGATE,
    OUTSKIRTS_CRONE_SHACK_INVESTIGATE,

    OUTSKIRTS_CRONE_TALK,
    OUTSKIRTS_JACK_TALK,

    // Cave.
    CAVE_SPRING_INVESTIGATE,
    CAVE_CORPSEC_INVESTIGATE,

    CAVE_VILLE_TALK,

    // Settlement.
    SETTLEMENT_ROAD_SIGN_INVESTIGATE,
    SETTLEMENT_BLACKSMITH_INVESTIGATE,
    SETTLEMENT_FARM_INVESTIGATE,
    SETTLEMENT_DUNGEON_INVESTIGATE,
    SETTLEMENT_FOUNTAIN_INVESTIGATE,
    SETTLEMENT_TAVERN_INVESTIGATE,
    SETTLEMENT_CHOBO_HOUSE_INVESTIGATE,

    SETTLEMENT_SMITH_TALK,
    SETTLEMENT_CHOBO_TALK,

    // House.
    HOUSE_CAULDRON_INVESTIGATE,
    HOUSE_BOOK_SHELF_INVESTIGATE,
    HOUSE_BOOK_INVESTIGATE,
    HOUSE_MEAD_INVESTIGATE,
    HOUSE_BED_INVESTIGATE,

    // Dungeon.
    DUNGEON_SCROLL_INVESTIGATE,
    DUNGEON_ROOM_ONE_GATE_INVESTIGATE,
    DUNGEON_BOOK_ONE_INVESTIGATE,
    DUNGEON_HARPSICHORD_INVESTIGATE,
    DUNGEON_RUNE_INVESTIGATE,
    DUNGEON_ROOM_FOUR_DOOR_INVESTIGATE,
    DUNGEON_CHEST_INVESTIGATE,
    DUNGEON_ROOM_TWO_DOOR_INVESTIGATE,

    DUNGEON_RUDOLF_TALK,
    DUNGEON_SLAVE_TALK
}
