package eu.janschupke.buddy.framework.config.enumeration.interaction;

/**
 * Enumeration of tags for all interaction decisions in the game.
 *
 * @author jan.schupke@gmail.com
 */
public enum DecisionTags {
    // TODO: use more globals.
    // Global.
    GLOBAL_END,

    // Forest.
    FOREST_COIN_PICKUP, FOREST_COIN_IGNORE,
    FOREST_UKKO_DELIVERY, FOREST_UKKO_END,

    // Outskirts.
    OUTSKIRTS_LUMBER_LEAVE, OUTSKIRTS_VARPUNEN_NOTE_LEAVE,
    OUTSKIRTS_CAVE_LEAVE, OUTSKIRTS_CRONE_SHACK_LEAVE,
    OUTSKIRTS_JACK_HOUSE_LEAVE, OUTSKIRTS_ROAD_SIGN_LEAVE,
    OUTSKIRTS_CRONE_LEAVE, OUTSKIRTS_JACK_LEAVE,

    // Cave.
    CAVE_VILLE_LEAVE, CAVE_CORPSEC_LEAVE, CAVE_SPRING_LEAVE,

    // House.
    HOUSE_BOOK_LEAVE, HOUSE_MEAD_LEAVE, HOUSE_BOOKSHELF_LEAVE,
    HOUSE_BED_LEAVE, HOUSE_CAULDRON_LEAVE,

    // Dungeon.
    DUNGEON_BOOK_ONE_LEAVE, DUNGEON_CHEST_LEAVE, DUNGEON_RUNE_LEAVE, DUNGEON_SCROLL_LEAVE,
    DUNGEON_HARPSICHORD_LEAVE, DUNGEON_ROOM_FOUR_DOOR_LEAVE, DUNGEON_ROOM_ONE_GATE_LEAVE,
    DUNGEON_ROOM_TWO_DOOR_LEAVE,
    DUNGEON_SLAVE_LEAVE, DUNGEON_RUDOLF_LEAVE
}
