package eu.janschupke.buddy.framework.config.enumeration;

/**
 * Enumeration of tags for all interaction decisions in the game.
 *
 * @author jan.schupke@gmail.com
 */
public enum DecisionTags {
    GLOBAL_END,
    FOREST_COIN_PICKUP, FOREST_COIN_IGNORE,
    FOREST_UKKO_DELIVERY, FOREST_UKKO_END,
    CAVE_VILLE_LEAVE, CAVE_CORPSEC_LEAVE, CAVE_SPRING_LEAVE,
    DUNGEON_BOOK_ONE_LEAVE, DUNGEON_CHEST_LEAVE, DUNGEON_RUNE_LEAVE, DUNGEON_SCROLL_LEAVE,
    DUNGEON_HARPSICHORD_LEAVE, DUNGEON_ROOM_FOUR_DOOR_LEAVE, DUNGEON_ROOM_ONE_GATE_LEAVE,
    DUNGEON_ROOM_TWO_DOOR_LEAVE,
    DUNGEON_SLAVE_LEAVE, DUNGEON_RUDOLF_LEAVE
}
