package eu.janschupke.tale_analyzer.entity.measurement.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;

/**
 * Represents the model of all possible game actions and their descriptions,
 * loaded from XML, generated by game.
 *
 * @author jan.schupke@gmail.com
 */
public class GameEventModel extends Observable implements Serializable {
    protected List<GameEvent> events;

    public GameEventModel() {
        events = new ArrayList<>();
    }

    public void reset() {
        events.clear();

        setChanged();
        notifyObservers();
    }

    public void load(GameEventModel gameEventModel) {
        events = gameEventModel.getEvents();

        setChanged();
        notifyObservers();
    }

    public List<GameEvent> getEvents() {
        return events;
    }
}
