package eu.janschupke.tale.content.config.enumeration.tags;

/**
 * Enumeration of tags for all game log entries.
 *
 * @author jan.schupke@gmail.com
 */
public enum GameEventTags {
    // Global.
    GLOBAL_NEW_GAME,

    // Forest.
    FOREST_EXPLORATION_EAST,
    FOREST_EXPLORATION_NORTH,
    FOREST_EXPLORATION_SOUTH,

    FOREST_GENERAL_INITIAL_WALL_CONTACT,
    FOREST_GENERAL_INTRO_CONTACT,
    FOREST_GENERAL_ITEM_INTRO_CONTACT,
    FOREST_GENERAL_QUEST_WALL_CONTACT,
    FOREST_GENERAL_UNIT_INTRO_CONTACT,

    FOREST_INTERACTION_CARAVAN,
    FOREST_INTERACTION_COIN,
    FOREST_INTERACTION_UKKO_DELIVERY,
    FOREST_INTERACTION_UKKO,

    FOREST_PICKUP_COIN,

    FOREST_TRANSITION_OUTSKIRTS,

    // Outskirts.
    OUTSKIRTS_EXPLORATION_CAVE,
    OUTSKIRTS_EXPLORATION_JACK,
    OUTSKIRTS_EXPLORATION_VARPUNEN,

    OUTSKIRTS_INTERACTION_CAVE,
    OUTSKIRTS_INTERACTION_CRONE,
    OUTSKIRTS_INTERACTION_CRONE_SHACK,
    OUTSKIRTS_INTERACTION_JACK_HOUSE,
    OUTSKIRTS_INTERACTION_JACK,
    OUTSKIRTS_INTERACTION_LUMBER,
    OUTSKIRTS_INTERACTION_ROAD_SIGN,
    OUTSKIRTS_INTERACTION_VARPUNEN,

    OUTSKIRTS_PICKUP_LUMBER,
    OUTSKIRTS_PICKUP_VARPUNEN,

    OUTSKIRTS_TRANSITION_CAVE,
    OUTSKIRTS_TRANSITION_FOREST,
    OUTSKIRTS_TRANSITION_SETTLEMENT,

    // Cave.
    CAVE_EXPLORATION_CORPSEC,

    CAVE_INTERACTION_CORPSEC,
    CAVE_INTERACTION_VILLE,

    CAVE_TRANSITION_OUTSKIRTS,

    // Settlement.
    SETTLEMENT_EXPLORATION_CHOBO,
    SETTLEMENT_EXPLORATION_DUNGEON,

    SETTLEMENT_INTERACTION_CHOBO_HOUSE,
    SETTLEMENT_INTERACTION_CHOBO,
    SETTLEMENT_INTERACTION_DUNGEON,
    SETTLEMENT_INTERACTION_FARM,
    SETTLEMENT_INTERACTION_FOUNTAIN,
    SETTLEMENT_INTERACTION_ROAD_SIGN,
    SETTLEMENT_INTERACTION_SMITH_HOUSE,
    SETTLEMENT_INTERACTION_SMITH,
    SETTLEMENT_INTERACTION_TAVERN,

    SETTLEMENT_TRANSITION_DUNGEON,
    SETTLEMENT_TRANSITION_OUTSKIRTS,
    SETTLEMENT_TRANSITION_HOUSE,

    // House.
    HOUSE_EXPLORATION_CLOSE,
    HOUSE_EXPLORATION_ROOM,

    HOUSE_INTERACTION_BED,
    HOUSE_INTERACTION_BOOK,
    HOUSE_INTERACTION_BOOKSHELF,
    HOUSE_INTERACTION_MEAD,

    HOUSE_PICKUP_BOOK,
    HOUSE_PICKUP_MEAD,

    HOUSE_TRANSITION_SETTLEMENT,

    // Dungeon.
    DUNGEON_EXPLORATION_STUDY,

    DUNGEON_INTERACTION_BOOK,
    DUNGEON_INTERACTION_CHEST,
    DUNGEON_INTERACTION_DOOR,
    DUNGEON_INTERACTION_GATE,
    DUNGEON_INTERACTION_HARPSICHORD,
    DUNGEON_INTERACTION_SCROLL,

    DUNGEON_TRANSITION_EXIT,
    DUNGEON_TRANSITION_SETTLEMENT,
}
