package eu.janschupke.tale.content.config.enumeration.tags;

/**
 * Enumeration of tags for all situations in the game.
 *
 * @author jan.schupke@gmail.com
 */
public enum SituationTags {
    // Forest.
    FOREST_COIN_INVESTIGATE,
    FOREST_CARAVAN_INVESTIGATE,

    FOREST_UKKO_TALK,
    FOREST_UKKO_DISCUSS,
    FOREST_UKKO_DELIVERY_RESULT,

    // Outskirts.
    OUTSKIRTS_LUMBER_INVESTIGATE,
    OUTSKIRTS_ROAD_SIGN_INVESTIGATE,
    OUTSKIRTS_JACK_HOUSE_INVESTIGATE,
    OUTSKIRTS_VARPUNEN_INVESTIGATE,
    OUTSKIRTS_CAVE_INVESTIGATE,
    OUTSKIRTS_CRONE_SHACK_INVESTIGATE,

    OUTSKIRTS_CRONE_TALK,
    OUTSKIRTS_CRONE_VARPUNEN_SHOW,
    OUTSKIRTS_CRONE_VARPUNEN_GIVE,
    OUTSKIRTS_JACK_TALK,
    OUTSKIRTS_JACK_CRONE,
    OUTSKIRTS_JACK_LUMBER_REQUEST,
    OUTSKIRTS_JACK_LUMBER_ACCEPT,
    OUTSKIRTS_JACK_LUMBER_DONE,
    OUTSKIRTS_JACK_DISPUTE_INIT,
    OUTSKIRTS_JACK_DISPUTE_RETRY,
    OUTSKIRTS_JACK_DISPUTE_ACCEPT,
    OUTSKIRTS_JACK_DISPUTE_DONE,
    OUTSKIRTS_JACK_FAIL,

    // Cave.
    CAVE_CORPSEC_INVESTIGATE,
    CAVE_CORPSEC_SEARCH,

    CAVE_VILLE_TALK,
    CAVE_VILLE_BOOK_AGGRO,
    CAVE_VILLE_BOOK_INQUIRY,
    CAVE_VILLE_BOOK_LEAVE,

    // Settlement.
    SETTLEMENT_ROAD_SIGN_INVESTIGATE,
    SETTLEMENT_BLACKSMITH_INVESTIGATE,
    SETTLEMENT_FARM_INVESTIGATE,
    SETTLEMENT_DUNGEON_INVESTIGATE,
    SETTLEMENT_FOUNTAIN_INVESTIGATE,
    SETTLEMENT_TAVERN_INVESTIGATE,
    SETTLEMENT_CHOBO_HOUSE_INVESTIGATE,

    SETTLEMENT_SMITH_TALK,
    SETTLEMENT_SMITH_ASSISTANCE,
    SETTLEMENT_SMITH_ACCEPT,
    SETTLEMENT_SMITH_RAMBLE,
    SETTLEMENT_CHOBO_TALK,
    SETTLEMENT_CHOBO_JOURNAL,
    SETTLEMENT_CHOBO_HOUSE,
    SETTLEMENT_CHOBO_JOURNAL_DELIVERED,
    SETTLEMENT_CHOBO_KEY_DELIVERED,
    SETTLEMENT_CHOBO_DUNGEON,

    // Dungeon.
    DUNGEON_GATE_INVESTIGATE,
    DUNGEON_HARPSICHORD_INVESTIGATE,
    DUNGEON_CHEST_INVESTIGATE,
    DUNGEON_CHEST_SEARCH,
}
